name = "EpdTest"
uuid = "34528f4c-2898-4a1e-84db-f60ead8305d0"
authors = ["lukas <lukas.arnroth@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
